name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy

    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup SSH and Deploy
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        run: |
          # Start SSH agent
          eval $(ssh-agent -s)

          # Add private key to SSH agent
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null

          # SSH into EC2 instance and deploy
          ssh -o ConnectTimeout=60 -o StrictHostKeyChecking=no ubuntu@3.82.129.106 << 'EOF'
            set -e  # Stop execution if any command fails
            
            echo "🚀 Navigating to project directory..."
            cd /home/ubuntu/hngx-stage2-fastapi-project || exit 1

            echo "🔄 Resetting repository..."
            git fetch --all
            git reset --hard origin/main  # Ensures a clean state
            git pull origin main

            echo "📦 Activating virtual environment..."
            source venv/bin/activate

            echo "⚡ Installing dependencies with caching..."
            pip install --no-cache-dir --upgrade -r requirements.txt

            echo "🔄 Restarting FastAPI service..."
            sudo systemctl restart fastapi

            echo "✅ Deployment completed successfully!"
          EOF
