name: cd pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_SSH_HOST }}
          username: ${{ secrets.EC2_SSH_USERNAME }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            # Navigate to the project directory
            cd /home/ubuntu/

            # Clone the repository only if it doesn't exist
            if [ ! -d "fastapi-book-project" ]; then
              git clone https://github.com/alibaba0010/fastapi-book-project.git
            fi

            # Enter the project directory
            cd fastapi-book-project

            # Pull latest changes
            git pull origin main

            # Ensure Docker and Docker Compose are installed (Run once)
            if ! command -v docker &> /dev/null; then
              sudo apt-get update -y
              sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
              curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
              sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
              sudo apt-get update -y
              sudo apt-get install -y docker-ce docker-ce-cli containerd.io
              sudo usermod -aG docker ${{ secrets.EC2_SSH_USERNAME }}
            fi

            if ! command -v docker-compose &> /dev/null; then
              sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
              sudo chmod +x /usr/local/bin/docker-compose
            fi

            # Stop and remove previous containers before redeploying
            docker-compose down || true

            # Build and restart containers
            docker-compose up -d --build
